name: main

on:
  push:
    branches: [ pile ]
  pull_request:
    branches: [ pile ]

jobs:
  test-pile-application:
    runs-on: ubuntu-20.04
    steps:
    - name: Setup git
      run: |
        git config --global user.email "playground-bot@my-domain.com"
        git config --global user.name "Playground Bot"
        git config --global init.defaultBranch main

    - name: Fetch git-pile
      uses: actions/checkout@v2
      with:
        repository: git-pile/git-pile
        path: git-pile

    - name: Install git-pile
      uses: git-pile/automation/env-setup@main
      with:
        version: ./git-pile

    - name: Checkout detached pile branch
      uses: actions/checkout@v2
      with:
        ref: ${{ github.sha }}

    - name: Create branches
      uses: git-pile/automation/setup@main
      with:
        pile-branch-name: pile
        pile-branch-ref: ${{ github.sha }}
        result-branch-name: internal
        fetch-baseline: true

    - name: Fake build
      run: make
