name: main

on:
  push:
    branches: [ pile ]

jobs:
  test-pile-application:
    runs-on: ubuntu-20.04
    steps:
    - name: Install Dependencies
      uses: git-pile/automation/env-setup@main

    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.sha }}

    - name: Setup git
      run: |
        git config --global user.email "playground-bot@my-domain.com"
        git config --global user.name "Playground Bot"

    - name: Setup pile branches
      uses: git-pile/automation/setup@main
      with:
        pile-branch-name: pile
        pile-branch-ref: ${{ github.sha }}
        result-branch-name: internal
        fetch-baseline: true

    - name: test
      run: git-pile --version
