name: main

on:
  push:
    branches: [ pile ]

jobs:
  test-pile-application:
    runs-on: ubuntu-20.04
    steps:
    - name: Fetch git-pile
      uses: actions/checkout@v2
      with:
        repository: git-pile/git-pile
        path: git-pile
        ref: tip
    - name: Install git-pile
      run: |
        pip3 install tqdm
        pip3 install git-pile/

    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.sha }}

    - name: Setup git
      run: |
        git config --global user.email "playground-bot@my-domain.com"
        git config --global user.name "Playground Bot"
        git config --global init.defaultBranch main

    - name: Setup pile branches
      uses: git-pile/automation/setup@main
      with:
        pile-branch-name: pile
        pile-branch-ref: ${{ github.sha }}
        result-branch-name: internal
        fetch-baseline: true

    - name: test
      run: git-pile --version
